insert into USER_DETAILS values(1,'mala@gm.com','mala','paryani',1234)


Insert into GEN_ANW_ANWENDER values(1,1,'mala.p@volkswagen.com','123456.6',1,1,'mala','UOqwe1','sdf','paryani')
Insert into GEN_ANW_ANWENDER values(2,1,'mala.p1@volkswagen.com','123456.6',1,1,'yhygfvh','UOqwe2','sdf','ghjgj')
Insert into GEN_ANW_ANWENDER values(3,1,'mala.p1@volkswagen.com','123456.6',1,1,'yhygfvh','UOqwe3','sdf','ghjgj')
Insert into GEN_ANW_ANWENDER values(4,1,'mala.p1@volkswagen.com','123456.6',1,1,'yhygfvh','UOqwe4','sdf','ghjgj')
Insert into GEN_ANW_ANWENDER values(5,1,'mala.p1@volkswagen.com','123456.6',1,1,'yhygfvh','UOqwe5','sdf','ghjgj')



INSERT INTO GEN_SC_SYSTEM_CONFIG VALUES(1,1,1)
INSERT INTO GEN_SC_SYSTEM_CONFIG VALUES(2,1,2)
INSERT INTO GEN_SC_SYSTEM_CONFIG VALUES(3,2,1)
INSERT INTO GEN_SC_SYSTEM_CONFIG VALUES(4,3,4)



INSERT INTO GEN_SYS_SYSTEM VALUES(1,0,0,NULL,0,NULL,0,'VWAG_AP','I.SERVE','1234','FULLPERSISTED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ISERVEEEE')
INSERT INTO GEN_SYS_SYSTEM VALUES(2,0,0,NULL,0,NULL,0,'VWAG_AP','KSRM','1234','CallBACK',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'KSRM')
INSERT INTO GEN_SYS_SYSTEM VALUES(3,0,0,NULL,0,NULL,0,'VWAG_AP','ENA','1234','FULLPERSISTED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ENA')
INSERT INTO GEN_SYS_SYSTEM VALUES(4,0,0,NULL,0,NULL,0,'VWAG_AP','SKODA','1234','FULLPERSISTED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'SKODA')


INSERT INTO GEN_VG_VORGANG VALUES(1,NULL,1,NULL,NULL,NULL,DATEADD(day,1,CURRENT_DATE),DATEADD(day,1,CURRENT_DATE),NULL,NULL,1,1,NULL,'NEW',NULL,NULL,'UUUUISDDSDC-DSDSD',DATEADD(day,1,CURRENT_DATE))
INSERT INTO GEN_HIS_HISTORY VALUES(1,NULL,NULL,'NEW_PROCESS',NULL,'BESTSELLING','DELETED','UUUUISDDSDC-DSDSD','EVX',CURRENT_DATE,1,'UOqwe1',1)
